import type { Profile } from "@/types/app";

export const mockProfile: Profile = {
  login: "testuser",
  id: 1,
  node_id: "MDQ6VXNlcjE=",
  avatar_url: "https://example.com/avatar.jpg",
  gravatar_id: "",
  url: "https://api.github.com/users/testuser",
  html_url: "https://github.com/testuser",
  followers_url: "https://api.github.com/users/testuser/followers",
  following_url: "https://api.github.com/users/testuser/following{/other_user}",
  gists_url: "https://api.github.com/users/testuser/gists{/gist_id}",
  starred_url: "https://api.github.com/users/testuser/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/testuser/subscriptions",
  organizations_url: "https://api.github.com/users/testuser/orgs",
  repos_url: "https://api.github.com/users/testuser/repos",
  events_url: "https://api.github.com/users/testuser/events{/privacy}",
  received_events_url: "https://api.github.com/users/testuser/received_events",
  type: "User",
  site_admin: false,
  name: "Test User",
  blog: "",
  location: "",
  bio: "Test bio",
  public_gists: 0,
  followers: 100,
  following: 50,
  public_repos: 25,
  created_at: "2024-01-01T00:00:00Z",
  updated_at: "2024-01-01T00:00:00Z",
  user_view_type: "public",
};
