import type { Repo } from "@/types/app";

import { mockOwner } from "@tests/__mocks__/owner.mock";

export const mockRepoBase: Omit<Repo, "name" | "html_url" | "full_name"> = {
  id: 0,
  node_id: "",
  private: false,
  owner: mockOwner,
  description: "",
  fork: false,
  url: "",
  forks_url: "",
  keys_url: "",
  collaborators_url: "",
  teams_url: "",
  hooks_url: "",
  issue_events_url: "",
  events_url: "",
  assignees_url: "",
  branches_url: "",
  tags_url: "",
  blobs_url: "",
  git_tags_url: "",
  git_refs_url: "",
  trees_url: "",
  statuses_url: "",
  languages_url: "",
  stargazers_url: "",
  contributors_url: "",
  subscribers_url: "",
  subscription_url: "",
  commits_url: "",
  git_commits_url: "",
  comments_url: "",
  issue_comment_url: "",
  contents_url: "",
  compare_url: "",
  merges_url: "",
  archive_url: "",
  downloads_url: "",
  issues_url: "",
  pulls_url: "",
  milestones_url: "",
  notifications_url: "",
  labels_url: "",
  releases_url: "",
  deployments_url: "",
  created_at: "2024-01-01T00:00:00Z",
  updated_at: "2024-01-01T00:00:00Z",
  pushed_at: "2024-01-01T00:00:00Z",
  git_url: "",
  ssh_url: "",
  clone_url: "",
  svn_url: "",
  homepage: "",
  size: 0,
  stargazers_count: 0,
  watchers_count: 0,
  language: "TypeScript",
  has_issues: true,
  has_projects: true,
  has_downloads: true,
  has_wiki: true,
  has_pages: false,
  has_discussions: false,
  forks_count: 0,
  archived: false,
  disabled: false,
  open_issues_count: 0,
  license: {
    key: "mit",
    name: "MIT License",
    spdx_id: "MIT",
    url: "",
    node_id: "",
  },
  allow_forking: true,
  is_template: false,
  web_commit_signoff_required: false,
  topics: [],
  visibility: "public",
  forks: 0,
  open_issues: 0,
  watchers: 0,
  default_branch: "main",
};
